import { comics } from "../../catalogo.js";

const fileName = decodeURIComponent(location.pathname.split("/").pop() || "");
const volume = Object.values(comics).find((item) => item.fileName === fileName);
if (!volume) throw new Error(`Volume não encontrado no catálogo: ${fileName}`);
const number = Number(volume.title.match(/Volume\s+(\d+)/i)?.[1]);
const year = volume.id.match(/-(\d{4})$/)?.[1] || "";
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));
const cover = `Bleach%20%23${number}.png`;

document.title = `${volume.title} - Loner Mangá`;
document.querySelector('meta[name="description"]')?.setAttribute("content", volume.summary);
document.body.innerHTML = `<div class="site-shell"><aside class="sidebar"><a class="brand sidebar-fallback-brand" href="../../index.html"><span class="brand-mark">LM</span><span><strong>Loner Mangá</strong><small>Arquivo de mangás</small></span></a><nav class="wiki-nav sidebar-fallback-nav"><a href="../../index.html">HOME</a><a href="../../Universos/universos.html">Mangás</a><a href="../../pesquisar.html">Pesquisar</a><a href="../../ranking.html">Ranking de Usuários</a><a href="../../minha-loja.html">Minha Loja</a></nav></aside><div class="content-shell"><header class="topbar"></header><main class="wiki-page"><article class="article"><nav class="breadcrumbs"><a href="../../index.html">Início</a><span>/</span><a href="../../Universos/universos.html">Mangás</a><span>/</span><a href="bleach.html">Bleach</a><span>/</span><span>Volume ${number}</span></nav><header class="article-header"><h1>${escapeHtml(volume.title)}</h1><p class="lead">Volume ${number} de Bleach, publicado pela Shueisha em ${year}, reunindo os capítulos ${escapeHtml(volume.chapters)}.</p></header><section class="content-band"><h2>Resumo</h2><p>${escapeHtml(volume.summary)}</p></section><section class="content-band"><h2>Dados do Volume</h2><table class="data-table"><tbody><tr><th>Título</th><td>Bleach #${number}</td></tr><tr><th>Ano</th><td>${year}</td></tr><tr><th>Publicação</th><td>${escapeHtml(volume.publicationDate)}</td></tr><tr><th>Editora</th><td>Shueisha</td></tr><tr><th>Roteiro</th><td>Tite Kubo</td></tr><tr><th>Arte</th><td>Tite Kubo</td></tr><tr><th>Série</th><td><a href="bleach.html">Bleach</a></td></tr><tr><th>Capítulos</th><td>${escapeHtml(volume.chapters)}</td></tr><tr><th>Páginas</th><td>${volume.pageCount} páginas</td></tr></tbody></table></section></article><aside class="infobox"><h2>${escapeHtml(volume.title)}</h2><img src="${cover}" alt="Capa do volume ${number} de Bleach"><table><tbody><tr><th>Universo</th><td>Bleach</td></tr><tr><th>Série</th><td>Bleach</td></tr><tr><th>Editora</th><td>Shueisha</td></tr><tr><th>Publicação</th><td>${escapeHtml(volume.publicationDate)}</td></tr></tbody></table></aside></main><footer class="site-footer"><p>Loner Mangá é um projeto local de catalogação de mangás.</p></footer></div></div>`;
