import { mkdir, readFile, writeFile } from "node:fs/promises";

const output = new URL("../Mangás/Dogsred/", import.meta.url);
const volumes = JSON.parse(await readFile(new URL("dogsred-volumes.json", import.meta.url), "utf8"));
const base = "https://lohnner.github.io/Loner-Manga/Mang%C3%A1s/Dogsred";
await mkdir(output, { recursive: true });

const date = iso => new Intl.DateTimeFormat("pt-BR", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${iso}T00:00:00Z`));
const shell = (title, description, canonical, image) => `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${title} - Loner Mangá</title><link rel="icon" href="../../favicon.png"/><meta name="theme-color" content="#0a0d14"/><meta name="description" content="${description}"/><link rel="canonical" href="${canonical}"/><meta property="og:type" content="article"/><meta property="og:site_name" content="Loner Mangá"/><meta property="og:title" content="${title} - Loner Mangá"/><meta property="og:description" content="${description}"/><meta property="og:image" content="${image}"/><meta property="og:url" content="${canonical}"/><link rel="stylesheet" href="../../styles.css" data-loner-cache-bust/><script src="../../boot.js" data-loner-app="../../script.js"></script></head><body><div class="site-shell"><aside class="sidebar"><a class="brand sidebar-fallback-brand" href="../../index.html"><span class="brand-mark">LM</span><span><strong>Loner Mangá</strong><small>Arquivo de mangás</small></span></a><nav class="wiki-nav sidebar-fallback-nav"><a href="../../index.html">HOME</a><a href="../../Universos/universos.html">Mangás</a><a href="../../pesquisar.html">Pesquisar</a><a href="../../ranking.html">Ranking de Usuários</a></nav></aside><div class="content-shell"><header class="topbar"></header>`;
const end = `<footer class="site-footer"><p>Loner Mangá é um projeto local de catalogação de mangás.</p></footer></div></div></body></html>\n`;
const description = "Mangá esportivo de Satoru Noda sobre um ex-patinador artístico que encontra um novo caminho competitivo no hóquei no gelo.";
const cards = volumes.map(v => `<a class="volume-card" href="dogsred-${v.number}-${v.releaseDate.slice(0, 4)}.html"><img src="Dogsred%20%23${v.number}.png" alt="Capa do volume ${v.number} de Dogsred" loading="lazy"/><span>Volume ${v.number}</span></a>`).join("");

await writeFile(new URL("dogsred.html", output), `${shell("Dogsred", description, `${base}/dogsred.html`, `${base}/Dogsred%20%231.png`)}<main class="wiki-page universe-layout"><article class="article"><nav class="breadcrumbs"><a href="../../index.html">Início</a><span>/</span><a href="../../Universos/universos.html">Mangás</a><span>/</span><span>Dogsred</span></nav><header class="article-header"><h1>Dogsred</h1><p class="lead">${description}</p></header><section class="content-band"><h2>Resumo do Mangá</h2><p>Rou Shirakawa era uma promessa da patinação artística, mas um colapso durante uma competição encerra sua carreira. Ao se mudar para Hokkaido, ele conhece o hóquei no gelo e descobre que sua habilidade sobre os patins pode ganhar um novo significado.</p><p>Entre treinos intensos, rivalidades e partidas violentas, Rou precisa aprender a trabalhar em equipe e transformar a frustração do passado em determinação para competir pelo colégio Oinokami.</p></section><section class="content-band"><h2>Informações do Mangá</h2><table class="data-table"><tbody><tr><th>Autor</th><td>Satoru Noda</td></tr><tr><th>Editora</th><td>Shueisha</td></tr><tr><th>Revista</th><td>Weekly Young Jump</td></tr><tr><th>Publicação</th><td>2023 – em andamento</td></tr><tr><th>Volumes</th><td>8</td></tr><tr><th>Capítulos</th><td>72 publicados; 1 a 65 encadernados</td></tr></tbody></table></section><section class="content-band"><h2>Volumes</h2><div class="volume-gallery">${cards}</div></section></article></main>${end}`);

const arc = chapter => chapter <= 7 ? "a transição de Rou da patinação artística para o hóquei no gelo" : chapter <= 24 ? "a chegada ao colégio Oinokami, a seleção da equipe e os primeiros treinos no gelo" : chapter <= 40 ? "a formação dos novatos e a partida de treinamento contra o colégio Sekka" : chapter <= 48 ? "o treinamento independente, a preparação do uniforme e o torneio de habilidades" : "a estreia oficial de Oinokami e os confrontos do campeonato colegial";
for (const v of volumes) {
  const year = v.releaseDate.slice(0, 4), [first, last] = v.chapters, file = `dogsred-${v.number}-${year}.html`, cover = `Dogsred%20%23${v.number}.png`, title = `Dogsred / Volume ${v.number}`;
  const summary = `Volume ${v.number} de Dogsred, de Satoru Noda, reunindo os capítulos ${first} a ${last}.`;
  await writeFile(new URL(file, output), `${shell(title, summary, `${base}/${file}`, `${base}/${cover}`)}<main class="wiki-page"><article class="article"><nav class="breadcrumbs"><a href="../../index.html">Início</a><span>/</span><a href="../../Universos/universos.html">Mangás</a><span>/</span><a href="dogsred.html">Dogsred</a><span>/</span><span>Volume ${v.number}</span></nav><header class="article-header"><h1>${title}</h1><p class="lead">${summary}</p></header><section class="content-band"><h2>Resumo</h2><p>Este volume desenvolve ${arc(first)}.</p><p>A história avança pelos acontecimentos reunidos nos capítulos ${first} a ${last}.</p></section><section class="content-band"><h2>Dados do Volume</h2><table class="data-table"><tbody><tr><th>Título</th><td>Dogsred #${v.number}</td></tr><tr><th>Ano</th><td>${year}</td></tr><tr><th>Publicação</th><td>${date(v.releaseDate)}</td></tr><tr><th>Editora</th><td>Shueisha</td></tr><tr><th>Roteiro e arte</th><td>Satoru Noda</td></tr><tr><th>Série</th><td><a href="dogsred.html">Dogsred</a></td></tr><tr><th>Capítulos</th><td>${first} a ${last}</td></tr><tr><th>Páginas</th><td>${v.pageCount} páginas</td></tr></tbody></table></section></article><aside class="infobox"><h2>${title}</h2><img src="${cover}" alt="Capa do volume ${v.number} de Dogsred"/><table><tbody><tr><th>Universo</th><td>Dogsred</td></tr><tr><th>Editora</th><td>Shueisha</td></tr><tr><th>Publicação</th><td>${date(v.releaseDate)}</td></tr><tr><th>Capítulos</th><td>${first} a ${last}</td></tr></tbody></table></aside></main>${end}`);
}

const catalogPath = new URL("../catalogo.js", import.meta.url); let catalog = await readFile(catalogPath, "utf8");
catalog = catalog.replace(/  \/\/ DOGSRED_COMPLETE_CATALOG[\s\S]*?  \/\/ DOGSRED_COMPLETE_CATALOG_END\n/, "");
const seriesEntry = `  { tipo: "serie", id: "dogsred-2023", title: "Dogsred", year: "2023", universe: "Dogsred", href: "Mangás/Dogsred/dogsred.html" },`;
const entries = volumes.map(v => { const year = v.releaseDate.slice(0, 4); return `  { tipo: "hq", id: "dogsred-${v.number}-${year}", title: "Dogsred / Volume ${v.number}", shortTitle: "Dogsred / Volume ${v.number}", universe: "Dogsred", series: "Dogsred", href: "Mangás/Dogsred/dogsred-${v.number}-${year}.html", cover: "Mangás/Dogsred/Dogsred%20%23${v.number}.png", pageCount: ${v.pageCount}, xpReward: ${v.pageCount}, fileName: "dogsred-${v.number}-${year}.html", publicationDate: "${date(v.releaseDate)}", chapters: "${v.chapters[0]} a ${v.chapters[1]}", keywords: ["Dogsred", "Volume ${v.number}", "Satoru Noda", "Rou Shirakawa", "hóquei no gelo", "Shueisha"] },`; }).join("\n");
catalog = catalog.replace("  // ALIEN_HEADBUTT_COMPLETE_CATALOG", `  // DOGSRED_COMPLETE_CATALOG\n${seriesEntry}\n${entries}\n  // DOGSRED_COMPLETE_CATALOG_END\n  // ALIEN_HEADBUTT_COMPLETE_CATALOG`); await writeFile(catalogPath, catalog);

const sitemapPath = new URL("../sitemap.xml", import.meta.url); let sitemap = await readFile(sitemapPath, "utf8"); sitemap = sitemap.replace(/\s*<url>\s*<loc>[^<]*\/Dogsred\/[^<]*<\/loc>\s*<\/url>/g, "");
const urls = [`${base}/dogsred.html`, ...volumes.map(v => `${base}/dogsred-${v.number}-${v.releaseDate.slice(0, 4)}.html`)].map(url => `  <url><loc>${url}</loc></url>`).join("\n"); sitemap = sitemap.replace("</urlset>", `${urls}\n</urlset>`); await writeFile(sitemapPath, sitemap);
console.log("Dogsred: 8 volumes, capítulos encadernados 1 a 65, catálogo e sitemap atualizados.");
