import { mkdir, readFile, writeFile } from "node:fs/promises";

const output = new URL("../Mangás/Monster/", import.meta.url);
const volumes = JSON.parse(await readFile(new URL("monster-volumes.json", import.meta.url), "utf8"));
const base = "https://lohnner.github.io/Loner-Manga/Mang%C3%A1s/Monster";
await mkdir(output, { recursive: true });

const date = iso => new Intl.DateTimeFormat("pt-BR", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${iso}T00:00:00Z`));
const shell = (title, description, canonical, image) => `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${title} - Loner Mangá</title><link rel="icon" href="../../favicon.png"/><meta name="theme-color" content="#0a0d14"/><meta name="description" content="${description}"/><link rel="canonical" href="${canonical}"/><meta property="og:type" content="article"/><meta property="og:site_name" content="Loner Mangá"/><meta property="og:title" content="${title} - Loner Mangá"/><meta property="og:description" content="${description}"/><meta property="og:image" content="${image}"/><meta property="og:url" content="${canonical}"/><link rel="stylesheet" href="../../styles.css" data-loner-cache-bust/><script src="../../boot.js" data-loner-app="../../script.js"></script></head><body><div class="site-shell"><aside class="sidebar"><a class="brand sidebar-fallback-brand" href="../../index.html"><span class="brand-mark">LM</span><span><strong>Loner Mangá</strong><small>Arquivo de mangás</small></span></a><nav class="wiki-nav sidebar-fallback-nav"><a href="../../index.html">HOME</a><a href="../../Universos/universos.html">Mangás</a><a href="../../pesquisar.html">Pesquisar</a><a href="../../ranking.html">Ranking de Usuários</a></nav></aside><div class="content-shell"><header class="topbar"></header>`;
const end = `<footer class="site-footer"><p>Loner Mangá é um projeto local de catalogação de mangás.</p></footer></div></div></body></html>\n`;
const description = "Thriller de Naoki Urasawa sobre o neurocirurgião Kenzo Tenma e as consequências de salvar a vida do jovem Johan Liebert.";
const cards = volumes.map(v => `<a class="volume-card" href="monster-${v.number}-${v.releaseDate.slice(0, 4)}.html"><img src="Monster%20%23${v.number}.png" alt="Capa do volume ${v.number} de Monster" loading="lazy"/><span>Volume ${v.number}</span></a>`).join("");

await writeFile(new URL("monster.html", output), `${shell("Monster", description, `${base}/monster.html`, `${base}/Monster%20%231.png`)}<main class="wiki-page universe-layout"><article class="article"><nav class="breadcrumbs"><a href="../../index.html">Início</a><span>/</span><a href="../../Universos/universos.html">Mangás</a><span>/</span><span>Monster</span></nav><header class="article-header"><h1>Monster</h1><p class="lead">${description}</p></header><section class="content-band"><h2>Resumo do Mangá</h2><p>Na Alemanha de 1986, o brilhante médico japonês Kenzo Tenma decide operar um menino ferido em vez de atender à ordem de priorizar uma autoridade. Anos depois, ele descobre que a criança salva, Johan Liebert, tornou-se o centro de uma cadeia de assassinatos.</p><p>Acusado injustamente, Tenma atravessa a Alemanha e a República Tcheca em busca de Johan. A investigação revela experimentos, identidades apagadas e traumas que ligam Johan, sua irmã Nina e o orfanato Kinderheim 511.</p></section><section class="content-band"><h2>Informações do Mangá</h2><table class="data-table"><tbody><tr><th>Autor</th><td>Naoki Urasawa</td></tr><tr><th>Editora</th><td>Shogakukan</td></tr><tr><th>Revista</th><td>Big Comic Original</td></tr><tr><th>Publicação</th><td>1994 – 2001</td></tr><tr><th>Volumes</th><td>18</td></tr><tr><th>Capítulos</th><td>1 a 162</td></tr></tbody></table></section><section class="content-band"><h2>Volumes</h2><div class="volume-gallery">${cards}</div></section></article></main>${end}`);

const arc = chapter => chapter <= 16 ? "o encontro de Tenma com os gêmeos Liebert e o início da perseguição a Johan" : chapter <= 32 ? "os segredos do Kinderheim 511 e as primeiras pistas sobre o passado dos gêmeos" : chapter <= 50 ? "a caçada a Tenma e os acontecimentos que aproximam os personagens do rastro de Johan" : chapter <= 77 ? "a investigação em Munique, envolvendo Richard Braun, Schuwald e o livro do monstro sem nome" : chapter <= 104 ? "a passagem por Praga, as memórias de Grimmer e os mistérios da Mansão das Rosas" : chapter <= 131 ? "a fuga de Tenma, o retorno das memórias de Nina e a aproximação do confronto decisivo" : "os acontecimentos finais em Ruhenheim e o acerto de contas entre Tenma, Nina e Johan";
for (const v of volumes) {
  const year = v.releaseDate.slice(0, 4), [first, last] = v.chapters, file = `monster-${v.number}-${year}.html`, cover = `Monster%20%23${v.number}.png`, title = `Monster / Volume ${v.number}`;
  const summary = `Volume ${v.number} de Monster, de Naoki Urasawa, reunindo os capítulos ${first} a ${last}.`;
  await writeFile(new URL(file, output), `${shell(title, summary, `${base}/${file}`, `${base}/${cover}`)}<main class="wiki-page"><article class="article"><nav class="breadcrumbs"><a href="../../index.html">Início</a><span>/</span><a href="../../Universos/universos.html">Mangás</a><span>/</span><a href="monster.html">Monster</a><span>/</span><span>Volume ${v.number}</span></nav><header class="article-header"><h1>${title}</h1><p class="lead">${summary}</p></header><section class="content-band"><h2>Resumo</h2><p>Este volume desenvolve ${arc(first)}.</p><p>A narrativa avança pelos acontecimentos reunidos nos capítulos ${first} a ${last}, sob o título editorial “${v.title}”.</p></section><section class="content-band"><h2>Dados do Volume</h2><table class="data-table"><tbody><tr><th>Título</th><td>Monster #${v.number}</td></tr><tr><th>Ano</th><td>${year}</td></tr><tr><th>Publicação</th><td>${date(v.releaseDate)}</td></tr><tr><th>Editora</th><td>Shogakukan</td></tr><tr><th>Roteiro e arte</th><td>Naoki Urasawa</td></tr><tr><th>Série</th><td><a href="monster.html">Monster</a></td></tr><tr><th>Capítulos</th><td>${first} a ${last}</td></tr><tr><th>Páginas</th><td>${v.pageCount} páginas</td></tr></tbody></table></section></article><aside class="infobox"><h2>${title}</h2><img src="${cover}" alt="Capa do volume ${v.number} de Monster"/><table><tbody><tr><th>Universo</th><td>Monster</td></tr><tr><th>Editora</th><td>Shogakukan</td></tr><tr><th>Publicação</th><td>${date(v.releaseDate)}</td></tr><tr><th>Capítulos</th><td>${first} a ${last}</td></tr></tbody></table></aside></main>${end}`);
}

const catalogPath = new URL("../catalogo.js", import.meta.url); let catalog = await readFile(catalogPath, "utf8");
catalog = catalog.replace(/  \/\/ MONSTER_COMPLETE_CATALOG[\s\S]*?  \/\/ MONSTER_COMPLETE_CATALOG_END\n/, "");
const seriesEntry = `  { tipo: "serie", id: "monster-1994", title: "Monster", year: "1994", universe: "Monster", href: "Mangás/Monster/monster.html" },`;
const entries = volumes.map(v => { const year = v.releaseDate.slice(0, 4); return `  { tipo: "hq", id: "monster-${v.number}-${year}", title: "Monster / Volume ${v.number}", shortTitle: "Monster / Volume ${v.number}", universe: "Monster", series: "Monster", href: "Mangás/Monster/monster-${v.number}-${year}.html", cover: "Mangás/Monster/Monster%20%23${v.number}.png", pageCount: ${v.pageCount}, xpReward: ${v.pageCount}, fileName: "monster-${v.number}-${year}.html", publicationDate: "${date(v.releaseDate)}", chapters: "${v.chapters[0]} a ${v.chapters[1]}", keywords: ["Monster", "Volume ${v.number}", "Naoki Urasawa", "Kenzo Tenma", "Johan Liebert", "Shogakukan"] },`; }).join("\n");
catalog = catalog.replace("  // MY_HERO_ACADEMIA_COMPLETE_CATALOG", `  // MONSTER_COMPLETE_CATALOG\n${seriesEntry}\n${entries}\n  // MONSTER_COMPLETE_CATALOG_END\n  // MY_HERO_ACADEMIA_COMPLETE_CATALOG`); await writeFile(catalogPath, catalog);

const sitemapPath = new URL("../sitemap.xml", import.meta.url); let sitemap = await readFile(sitemapPath, "utf8"); sitemap = sitemap.replace(/\s*<url>\s*<loc>[^<]*\/Monster\/[^<]*<\/loc>\s*<\/url>/g, "");
const urls = [`${base}/monster.html`, ...volumes.map(v => `${base}/monster-${v.number}-${v.releaseDate.slice(0, 4)}.html`)].map(url => `  <url><loc>${url}</loc></url>`).join("\n"); sitemap = sitemap.replace("</urlset>", `${urls}\n</urlset>`); await writeFile(sitemapPath, sitemap);
console.log("Monster: 18 volumes, capítulos 1 a 162, catálogo e sitemap atualizados.");
